# Generated by Django 4.2.2 on 2023-06-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=4)),
                ("make", models.CharField(max_length=30)),
                ("model", models.CharField(max_length=30)),
                ("miles", models.CharField(max_length=7)),
                ("extcolor", models.CharField(max_length=10)),
                ("VIN", models.CharField(max_length=4)),
            ],
        ),
    ]
